### ISSUE TITLE
Link in New Tab

### ISSUE THREAD

**Issue by carrodher** [Angelmmiguel/kip#51]
I think when you click on a link is better to open a new tab, so it is not out of the web of Kip and you can continue reading the article easily when you return to visit the external web

**Comment by Angelmmiguel** [comment]
👍  I think it's better too, because when you write an article, links are usually external references. I will implement it for external links.

**Comment by Angelmmiguel** [comment]
We can use the option `:link_attributes` from [RedCarpet](https://github.com/vmg/redcarpet#darling-i-packed-you-a-couple-renderers-for-lunch)
