### ISSUE TITLE
Create an editor

### ISSUE THREAD

**Issue by Angelmmiguel** [Angelmmiguel/kip#6]
The editor must be focused on content creation, so it won't have any distraction in the interface. In conclusion, the design will be clear.

We can check articles like [Is Web Typography Completely Broken?](http://zellwk.com/blog/web-typography-broken/) or [Why is Vertical Rhythm an Important Typography Practice?](http://zellwk.com/blog/why-vertical-rhythms/) to create a nice environment to write.

**Comment by juliojgarciaperez** [comment]
May we use an external plugin/gem to implement the text editor?

Design our own would be quite hard, including memento pattern and other issues

**Comment by Angelmmiguel** [comment]
I think in a text editor as a simple text box. With Markdown, we don't need to add any button/bar.

**Comment by Angelmmiguel** [comment]
I create the first version of the editor. It's focused on writing deleting all distractions. I add a counter of words and an estimation of read time.

<img width="1267" alt="editor" src="https://cloud.githubusercontent.com/assets/4056725/14233749/ae93ed22-f9d1-11e5-9bfa-f7bbd9053c83.png">

**Comment by Angelmmiguel** [comment]
The next step is to validate the form, all fields are required.
